### ISSUE TITLE
On hotreload, locale is set back to the default one

### ISSUE THREAD

**Issue by joanofdart** [ilteoood/flutter_i18n#133]
Hello 👋🏼 
First of all, thank you for such a wonderful package. You guys are awesome!

I've been playing around with it and it seems like when I do a hot reload, the locale is set back to the devices one.
Just wondering if thats already reported or known? thanks!

**Comment by ilteoood** [comment]
Hi @joanofdart ,
which version of the library are you using?

To switch language, are you using the force method?
Can you past an example in order to reproduce the bug?
Can you reproduce the bug using the example app provided in this repository? I've tried with the namespace example, without luck.

Thank you for your kind words,

Matteo

**Comment by joanofdart** [comment]
hey @ilteoood ,

I'm using the latest version and I'm not doing anything fancy, just "hot reloading" on vscode. It then switches back to the "default locale".

I'm switching to a locale of my choosing using 

```
await FlutterI18n.refresh(context, Locale(newLocale));
```

**Comment by ilteoood** [comment]
What about the example provided in this repo?
There we use the refresh method, and with the hot reload the state is maintained.

**Comment by ilteoood** [comment]
any news about this?

**Comment by joanofdart** [comment]
hey @ilteoood 
Sorry about my absence, indeed following the example works like a charm.
I guess it needs to be strictly `loaded` before running the app.

Closing~
