### ISSUE TITLE
Expose API to get current locale

### ISSUE THREAD

**Issue by crizant** [ilteoood/flutter_i18n#16]
Hi, thanks for creating this awesome plugin.
Is there any ways to get the current locale?

**Comment by ilteoood** [comment]
Hi, to find system locale I use this function: https://docs.flutter.io/flutter/intl_standalone/findSystemLocale.html

The function that I wrote return a Locale instead of a String. If you prefer, I could make that method public.

**Comment by crizant** [comment]
Yes please, I see you stored a `locale` object in `FlutterI18n` instance, it would be useful if you make it public.

**Comment by ilteoood** [comment]
That object doesn't represent the system locale, but the locale used by the library for translation purposes.
I will make the _findCurrentLocale public and static.

**Comment by crizant** [comment]
Yes i would like to get the locale being used by the library. Thanks.

**Comment by ilteoood** [comment]
Why you need it?

**Comment by crizant** [comment]
Because my application would change language in runtime, I have an observable store to store the language that the app is using, when it changes, it triggers the component to re-render.
But first I have to know the locale currently using, in order to initialize the observable store.

**Comment by ilteoood** [comment]
Wait, you don't need to do this.
When the system language change, the library will load the new translation asset and will reload every translation.
Have you a detailed example? Other people do the same thing without this information.

**Comment by crizant** [comment]
Like [this example](https://github.com/ilteoood/flutter_i18n/blob/master/example/lib/main.dart) from you,
you have to have a state to hold the language, when it updates it triggers rebuild of the layout.
When you take it away, the layout won't rebuild when language changes.

**Comment by Quijx** [comment]
@ilteoood
I think @crizant has a point. I also have an application where the language is not dependent on the system language, but on a setting in a settings page.

I did a bit of research and I think that the proper way to control the language inside the app is to set the `locale` attribute inside the `MaterialApp` Widget. The value can be dynamic either with something like the `scoped_model` package or simply a `StatefulWidget`.

If the locale changes, the `load` method of the `LocalizationsDelegate` is called again with the given locale.

If the `locale` attribute is unset, the locale given to `load` is dependent on the system language priority list.
Sadly I could not find a lot of documentation on this, but I tested a bit and believe the algorithm for selecting the locale goes like this:

*Take the locale with the highest priority in the system language settings, that is also in the `supportedLocales` attribute in the `MaterialApp` Widget.
If none is found, use the first locale in the `supportedLocales` attribute.*

This also means that you shouldn't need a fallback file because the fallback locale is managed by flutter.

But since you are not using the `locale` that is given inside of `load` in your `FlutterI18nDelegate` class, switching the language this way does not work. (Also `FlutterI18n.refresh` is not working for me, but that might have a different reason.)

And when the locale is selected in this way, getting the current locale is really useful because I think the only alternative would be to create a custom `Delegate` that stores the locale somewhere when `load` is called.

You should take everything I just wrote with a grain of salt, as I am relatively new to flutter.

**Comment by ilteoood** [comment]
Hi @Quijx,
your analysis is correct and well formed.
The reason why I don't use the LocalizationsDelegate is to leave the possibility to override the fallback settings of the device (eg: English for everyone, even if the fallback language is Spanish). Also, with this approch, the entire widget tree isn't reloaded when the system language change.
I read your motivation and decided to approve this request. Will be available ASAP.

Thank you,
Matteo

**Comment by ilteoood** [comment]
Fixed with https://github.com/ilteoood/flutter_i18n/commit/9e56c9959d919459eaed2cbff3d5ea16c65c591e

Please pay attention to the breaking changes.

Thank you so much for your contribute,
Mattei
