### ISSUE TITLE
How to load specific language at first load?

### ISSUE THREAD

**Issue by jintangWang** [ilteoood/flutter_i18n#24]

**Comment by ilteoood** [comment]
You can use the refresh method

**Comment by jintangWang** [comment]
I user the refresh method at `home.dart`, which is my root route Widget. But the result is weird,  I use `FlutterI18n.refresh(context, ‘zh’);` and it seems not work at first load, after I navigator to other route, it works.

**Comment by ilteoood** [comment]
Try with the latest version, where there isn't a string as second parameter but a Locale object.

**Comment by jintangWang** [comment]
I have updated to '0.6.2',.Here is my code at `home.dart`'s `initState` method, `FlutterI18n.refresh(context, new Locale('zh'));`. But still face the same problem.

**Comment by ilteoood** [comment]
Example updated, check cbb6c906117d2444f6d64480ac2250d883f7f705 to know how to do it.

**Comment by Purus** [comment]
I treid this and I get a black screen on the page load. I had this issue  as in https://github.com/ilteoood/flutter_i18n/issues/17. But it was solved based on your comment.

This black screen issue happens when loading language at app start time. Any help please?

```
  final FlutterI18nDelegate flutterI18nDelegate = FlutterI18nDelegate(
      useCountryCode: false, fallbackFile: 'en', path: 'assets/i18n');

MaterialApp(
            title: 'Blouse Designs',
            theme: ThemeData(
              primarySwatch: Colors.pink,
            ),
            home: BlouseDesignApp(),
            localizationsDelegates: [
              flutterI18nDelegate,
              GlobalMaterialLocalizations.delegate,
              GlobalWidgetsLocalizations.delegate
            ],
          );
```

And in the body, I use the below code to load the language on app start.

```
  void init() async{
    String userLanguage =
        PrefsProvider.prefs.getString("userLanguage") ?? "en";
    await FlutterI18n.refresh(context, Locale(userLanguage));
  }

  @override
  Future initState() {
    super.initState();

    init();
}
```

It still starts the app in default language and not in the chosen language. Once I go to different page and come back, language is changed.
