### ISSUE TITLE
workflow

### ISSUE THREAD

**Issue by pouledodue** [ilteoood/flutter_i18n#4]
Hi
I like the simplicity of your approach
Regarding the workflow, what tool do you use to detect missing translations?
Example if I have 10 big nested json language files and somewhere in es.json is missing translated string for some.key.nested.hello, how do you detect that?

**Comment by ilteoood** [comment]
Hi,
I don't use any tool to do these checks.
The library load the required language file at runtime, only when you need it.
I treat the language file as a Map<String, dynamic>, where the dynamic part can be divided in:
- Map<String, dynamic>
- String

I use the translation key to walk inside this structure: if the path described is broken, I return the key used for the translation, otherwise the translation described in the .json file.

**Comment by gedw99** [comment]
@pouledodue Maybe you can use the golang tools for the workflow.

https://github.com/nicksnyder/go-i18n#command-goi18n-
