### ISSUE TITLE
Add Fallback language to translate method

### ISSUE THREAD

**Issue by dukaric1991** [ilteoood/flutter_i18n#63]
I just noticed u added fallback key to translate method. 

In my case i have around 15 supported languages in my app, and i know that English language/file contains all keys with translations. It would be nice to have fallback language, lets say i have some other language selected instead of English and the key is not found in "French" language file, it could use English translation as default.

like this:
`FlutterI18n.translate(context, "alert_title", "english")`

`"english"` parameter will be fallback language if key `"alert_title"` is not found in lets say French language file.

**Comment by ilteoood** [comment]
I don't like a sort of "hybrid" translation: in the case that you described, you can reach a situation where you can have half app in english and half in french...this doesn't sounds good.
I mean: if a key is missing, you have an incomplete translation file and you should fix it, otherwise find a missing key can be difficult.

**Comment by shlima** [comment]
It is strange that there is no support of fallback locale chain. In this case we have one localization file for a certain list of languages.

```dart
FlutterI18nDelegate(
   defaultLocale: "en", // previously known as `fallbackFile`
   fallbacks: { "be": ["ru"], "uk": ["ru"] }
)
```

**Comment by ilteoood** [comment]
To use this kind of chain during the translation the library should load 2 or more translation dictionary and this brings a slowdown during application startup.
If you want, I can implement a fallback chain in order to use different fallback languages.

**Comment by shlima** [comment]
IMHO boilerplate Flutter up takes around 50 MiB in memory. There will be no harm if the application loads an extra **5 KiB**  of data into a memory, however this will increase user experience (in countries where there are 2 or more official languages)

**Comment by shlima** [comment]
`Fallbacks` option is left to the discretion of a particular developer and will not affect all users of a library. You should load additional peace of data only if the user explicitly indicated them in the configuration.

After splash screen people may to draw a loading indicator since the real application makes network requests before launching and downloading additional 5 KiB from local storage does not play any role in the launch speed in this case.

**Comment by ilteoood** [comment]
I think that is not possible to draw a loading indicator: the delegate is instantiated before the home, so you can't draw any widget until the library is fully loaded.
Btw, I'm trying to search a solution...

**Comment by xavier-usitoo** [comment]
Hi, we face the same issue: it would be convenient/important to have a fallback. When adding new features, sometime urgently, it is not always possible to have all translators to finish their work in a rush. In the meantime it is critical for texts to appear in a default langue (e.g. English) rather than having JSON keys which the users have no chance to understand. 
Both of the above-mentioned mechanism (optional argument in function, or global settings) would do the job fine. Thanks for keeping us posted about that. 

NB: others i18n libraries tackle it, but yours is definitely the reference i18n lib for flutter. I would prefer to keep using yours ;-)

**Comment by ilteoood** [comment]
I'm thinking to introduce this asap.
The decoders implementation of the last week is a step in this direction.

**Comment by ilteoood** [comment]
I'm thinking to introduce this asap.
The decoders implementation of the last week is a step in this direction.

**Comment by ilteoood** [comment]
Starting with 0.15.0, the missing keys are retrieved from the fallback file.

**Comment by xavier-usitoo** [comment]
Works great, thank you very much for this upgrade !
